### ISSUE TITLE
建模回忆录 | TONY'S TOY BLOG

### ISSUE THREAD

**Issue by tonybro233** [tonybro233/Blog-Comment#40]
https://www.tony-bro.com/posts/1728549503/ 

 托尼哥的玩具博客

**Comment by Cangjier** [comment]
兄弟，你知道CAA 进行拓扑操作后的结果，GetResult()的CATBody怎么挂到特征树上去？

**Comment by tonybro233** [comment]
> @TidyScript
> 兄弟，你知道CAA 进行拓扑操作后的结果，GetResult()的CATBody怎么挂到特征树上去？

太细节，忘了。你可以找找QQ群去询问。
