### ISSUE TITLE
The First 4 Years | TONY'S TOY BLOG

### ISSUE THREAD

**Issue by tonybro233** [tonybro233/Blog-Comment#73]
https://www.tony-bro.com/posts/3196990035/ 

 托尼哥的玩具博客

**Comment by RoadTLife** [comment]
tony哥，我一直关注你的文章，加油。共勉吧，希望这条路是对的。

**Comment by tonybro233** [comment]
> @RoadTLife
> tony哥，我一直关注你的文章，加油。共勉吧，希望这条路是对的。
> 

来啦，老弟~！共勉共勉~ 🤪

**Comment by coooodeXjl** [comment]
gogogo 保持不断进步就好啦，不必过于悲观，大多数人都是狗样 hhhh

**Comment by tonybro233** [comment]
> @coooodeXjl
> gogogo 保持不断进步就好啦，不必过于悲观，大多数人都是狗样 hhhh

来啦，老弟~！但是泯然众人还是有点悲伤呢~🧐
